apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: rg.fr-par.scw.cloud/atut-group-1/backend
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: backend-volume
          mountPath: /backend
      volumes:
      - name: backend-volume
        hostPath:
          path: ./backend
          type: Directory