name: Build & Deploy to Scaleway
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Scaleway Container Registry
      run:  echo ${{ secrets.SCW_SECRET_KEY}} | docker login ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }} -u ${{secrets.SCW_SECRET_KEY}} --password-stdin
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/atut-bootcamp:abraham-koloboe
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/atut-bootcamp:abraham-koloboe